// Lists the footage and audio that exist under public/ and writes them to
// src/generated/assets.ts. The trailer reads that list to decide, per clip, whether
// to play the recording or draw a placeholder - so it renders before anything has
// been recorded, and every missing shot is visible in the preview.
import {readdirSync, mkdirSync, writeFileSync, existsSync} from 'node:fs';
import {join, relative, sep} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const pub = join(root, 'public');
const media = /\.(mp4|mov|mkv|webm|ogg|mp3|wav|flac|aac|m4a)$/i;

const walk = (dir) =>
  !existsSync(dir)
    ? []
    : readdirSync(dir, {withFileTypes: true}).flatMap((entry) => {
        const path = join(dir, entry.name);
        return entry.isDirectory() ? walk(path) : media.test(entry.name) ? [path] : [];
      });

const files = ['clips', 'audio', 'pack']
  .flatMap((dir) => walk(join(pub, dir)))
  .map((path) => relative(pub, path).split(sep).join('/'))
  .sort();

mkdirSync(join(root, 'src', 'generated'), {recursive: true});
writeFileSync(
  join(root, 'src', 'generated', 'assets.ts'),
  `// Generated by scripts/scan-assets.mjs. Do not edit.\nexport const availableAssets: readonly string[] = ${JSON.stringify(files, null, 2)};\n`,
);
console.log(`assets: ${files.length} media file(s) under public/`);
